<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>10</LangVersion>
        <RootNamespace>FolderIcons</RootNamespace>
        <Nullable>disable</Nullable>
        <RunPostBuildEvent>Always</RunPostBuildEvent>
    </PropertyGroup>

    <PropertyGroup>
        <OutputPath>$(SPZ2_PERSISTENT)\mods\FolderIcons</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);CS0436</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Update="manifest.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <PropertyGroup>
        <MonoModRuntimeDir Condition="'$(SPZ2_SHIFTER)' != ''">$([System.IO.Path]::GetDirectoryName('$(SPZ2_SHIFTER)'))\..\3542712030</MonoModRuntimeDir>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="ShapezShifter">
            <HintPath>$(SPZ2_SHIFTER)</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="MonoMod">
            <HintPath>$(MonoModRuntimeDir)\MonoMod.RuntimeDetour.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="MonoMod.Utils">
            <HintPath>$(MonoModRuntimeDir)\MonoMod.Utils.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Mono.Cecil">
            <HintPath>$(MonoModRuntimeDir)\Mono.Cecil.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Newtonsoft.Json">
            <HintPath>$(SPZ2_PATH)\Newtonsoft.Json.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Core">
            <HintPath>$(SPZ2_PATH)\Core.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Core.Localization">
            <HintPath>$(SPZ2_PATH)\Core.Localization.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core">
            <HintPath>$(SPZ2_PATH)\Game.Core.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Core.Modding">
            <HintPath>$(SPZ2_PATH)\Game.Core.Modding.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Hud">
            <HintPath>$(SPZ2_PATH)\Game.Hud.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Hud.View">
          <HintPath>$(SPZ2_PATH)\Game.Hud.View.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Hud.View.Model">
          <HintPath>$(SPZ2_PATH)\Game.Hud.View.Model.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Interaction">
          <HintPath>$(SPZ2_PATH)\Game.Interaction.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Game.Orchestration">
            <HintPath>$(SPZ2_PATH)\Game.Orchestration.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="SPZGameAssembly">
            <HintPath>$(SPZ2_PATH)\SPZGameAssembly.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Toolbar">
            <HintPath>$(SPZ2_PATH)\Toolbar.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UIModule">
            <HintPath>$(SPZ2_PATH)\UnityEngine.UIModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <PropertyGroup>
        <PublicizeAll>true</PublicizeAll>
    </PropertyGroup>
</Project>
